#!/usr/bin/sh
###########################################################
#Write a bash script that prints the string "HELLO".     #
#Input Format                                            #
#There is no input file required for this problem.       #
#Output Format                                           #
#HELLO                                                   #
#Sample Input                                            #
#-                                                       #
#Sample Output                                           #
#HELLO                                                   #
#Explanation                                             #
#https://www.hackerrank.com/challenges/bash-tutorials-lets-echo/problem #
##########################################################

echo 'HELLO'
